# .github/workflows/docs.yml
name: Docs checks
on: [push, pull_request]
jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --no-progress --verbose --exclude-mail
            './**/*.md'
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: davidanson/markdownlint-cli2-action@v16
        with:
            globs: |
              **/*.md
              **/*.markdown

